# Usamos una imagen base de Node.js
FROM node:18 AS build

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos el archivo package.json y package-lock.json para instalar las dependencias
COPY package*.json ./

# Instalamos las dependencias
RUN npm install

# Copiamos todo el código del backend al contenedor
COPY . .

# Compilamos el proyecto de TypeScript
RUN npm run build

# Establecemos el contenedor como ejecutable del servicio
CMD ["npm", "run", "start:prod"]

# Exponemos el puerto donde la app escuchará (generalmente 3000 para NestJS)
EXPOSE 3000
